### ISSUE TITLE
Comparison with change-inner package?

### ISSUE THREAD

**Issue by kaushalmodi** [cs14095/ciel.el#4]
Hi,

I haven't used either this package or the [`change-inner`](https://github.com/magnars/change-inner.el) package by Magnar.

But I was simply aware of that package and I saw this one show up as a new package on Melpa.

Would you take some time to compare the two packages? If possible, would it be better to send PR's to the older change-inner package?

_Just my few cents._

Thanks.

**Comment by cs14095** [comment]
Hi, @kaushalmodi . 

I should describe that anywhere.
I know the package `change-inner.el`. 
But to be honest, I didn't know it when I made this package.
I thought I should delete this when I found `change-inner.el`.

However, `change-inner.el` has some issue I think.
- It depends on expand-region.el (Of course I know he is the developer of `expand-region.el`).
- It sometimes doesn't work in some mode because of `expand-region.el`.

and `ciel.el` is
- `ciel.el` probably works in any mode.
- It exactly works when it is "nested parentheses" like vim even if cursor is `{ { } (here) }`.
- It works without enter, for example just push `ciw` not `ciw(enter)`

This is for users who want to use `ci` command simply and exactly.
It works just like vim in the name of "clone". 
It's not possible to remove dependencies without changing his most code.
I think changing many code in his package is impolite isn't that?
His code is awesome and I respect him.

Thank you.

**Comment by kaushalmodi** [comment]
Thanks for the explanation. 

I do not use the `change-inner` package, so I could not comment on how this package and that can be merged in a harmonious way. I brought this up because I had heard of a package with similar intent.

I think it would be a good idea to put this analysis of how the 2 packages compare, in the README.

**Comment by cs14095** [comment]
Thank you.

I think it's difficult to merge with change-inner.el unfortunately.
The 2 codes are completely different.

You're right.
It would be good for anyone.

Thank you for comment!
